name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.5.0-rc1
homepage: https://github.com/flame-engine/flame_forge2d

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flame: ^1.0.0-rc2
  forge2d: ^0.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
